### ISSUE TITLE
How to compile mpv-git  with your ffmpeg-git 

### ISSUE THREAD

**Issue by eko5624** [deus0ww/homebrew-tap#2]
Thanks for your great work. I do some tests, always error. Any suggestion?
brew tap deus0ww/tap
brew install --HEAD deus0ww/tap/ffmpeg
brew install --HEAD deus0ww/tap/mpv

Maybe  ffmpeg.rb is broken HEAD.

**Comment by deus0ww** [comment]
Log?

**Comment by eko5624** [comment]
LOG is here. Please take a look, thanks.
https://github.com/eko5624/mpv-macos-test/runs/5587379372?check_suite_focus=true

[logs_80.zip](https://github.com/deus0ww/homebrew-tap/files/8287704/logs_80.zip)

**Comment by deus0ww** [comment]
This is likely due to recent ffmpeg commits starting with: https://github.com/FFmpeg/FFmpeg/commit/f2da2e1458b76a1d6c068673430b46cf2850bc51

mpv will probably need to make some changes. I would really appreciate it if you could report this to mpv...

Update: Apparently this is already known: https://github.com/mpv-player/mpv/pull/9987

**Comment by eko5624** [comment]
Got it. Thanks!

**Comment by deus0ww** [comment]
Fixed in mpv master in commit https://github.com/mpv-player/mpv/commit/f871294204529374dd3056f7b616381400233036
